import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FormProvider, useFormContext } from './context/FormContext';
import StepBasic from './steps/StepBasic';
import StepTrade from './steps/StepTrade';
import StepBusinessHours from './steps/StepBusinessHours';
import StepLocation from './steps/StepLocation';
import StepAbout from './steps/StepAbout';
import { LiaStoreSolid } from 'react-icons/lia';
import StoreSuccessOverlay from '../StoreSuccessOverlay';
import { createStore } from '../../../../features/stores/storeSlice';
import { useAppDispatch, useAppSelector } from '../../../../app/hooks';
import { createLayout } from '../../../../features/layouts/layoutSlice';
import { defaultLayoutConfig } from '../../../../utils/defaults/defaultLayoutConfig';
import StepSocials from './steps/StepSocials';
import StepDelivers from './steps/StepDelivers';
import { TbLoader3 } from 'react-icons/tb';
import { useNavigate } from 'react-router-dom';
import { IoClose } from 'react-icons/io5';

const steps = [StepBasic, StepTrade, StepBusinessHours, StepLocation, StepDelivers, StepAbout, StepSocials];
interface CreateStoreFormInnerProps {
    isDemo?: boolean;
}

const CreateStoreFormInner: React.FC<CreateStoreFormInnerProps> = ({ isDemo = false, }) => {
   const dispatch = useAppDispatch();
   const navigate = useNavigate();
   const { step, direction, nextStep, prevStep, validateCurrentStep, form, setNextClicked, clearDraft, resetForm } = useFormContext();
   const [isSuccess, setIsSuccess] = useState(false);
   const [submitError, setSubmitError] = useState<string | null>(null);
   const [ isSubmitting, setIsSubmitting ] = useState(false);
   const isLoading = useAppSelector((state) => state.stores.isLoading || state.layout.isLoading);
   const storeError = useAppSelector((state) => state.stores.error);
   const user = useAppSelector((state) => state.user.user);
  
  const StepComponent = steps[step];

  
  const handleNextStep = () => {
    setNextClicked(true);
    setSubmitError(null); // Clear any previous errors
    if (validateCurrentStep()) {
      nextStep();
    }
  };

  const handlePrevStep = () => {
    setSubmitError(null); // Clear any previous errors
    prevStep();
  };

  const handleClose = () => {
    if (window.confirm('Are you sure you want to close? Your progress will be saved as a draft.')) {
      navigate(-1);
    }
  };

  const handleReset = () => {
    if (window.confirm('Are you sure you want to start over? This will clear all your progress.')) {
      resetForm();
    }
  };
  
  const createNewLayout = async () => {
    try {// @ts-ignore-next-line
      const result = await dispatch(createLayout(defaultLayoutConfig)).unwrap();
      return result._id;
    } catch (error) {
      console.error('Failed to create layout:', error);
      return null;
    }
  };


  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);
    setIsSubmitting(true);
    
    try {
      // Validate all required fields before submission
      if (!form.name.trim()) {
        setSubmitError('Store name is required');
        return;
      }
      
      if (!form.contact.phone || !/^[0-9]{10}$/.test(form.contact.phone)) {
        setSubmitError('Valid phone number is required');
        return;
      }
      
      if (!form.contact.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.contact.email)) {
        setSubmitError('Valid email address is required');
        return;
      }
      
      if (!form.departments.length) {
        setSubmitError('Please select a department');
        return;
      }
      
      if (!form.location.address) {
        setSubmitError('Store location is required');
        return;
      }

      if (!user?._id) {
        setSubmitError('User authentication required. Please log in and try again.');
        return;
      }

      const storeData = {
        ...form,
        isDemo,
        slug: '', // Will be generated by backend
        description: form.about || '',
        thumbnails: {
          storeCard: form.thumbnail || '',
          profily: form.thumbnail || ''
        },
        website: {
          source: 'internal',
          layoutId: '',
        },
        categories: {
          products: [],
          services: [],
          rentals: [],
          donations: []
        },
        isVerified: false,
        likes: {
          count: 0,
          users: []
        },
        visits: 0,
        team: [{
          _id: user._id.toString(),
          member: user._id.toString(),
          username: user.username || '',
          firstName: user.firstName || '',
          lastName: user.lastName || '',
          about: '',
          role: 'owner' as const
        }],
        location: {
          type: 'Point',
          coordinates: [form.location.coordinates[0], form.location.coordinates[1]], // [lng, lat]
          nickname: form.location.nickname,
          address: form.location.address
        },
        socials: form.socials?.map(social => ({
          platform: social.platform as "facebook" | "twitter" | "instagram" | "linkedin" | "pinterest" | "youtube" | "whatsapp" | "phone",
          url: social.url
        })) || [],
        operationTimes: form.operationTimes as any // Cast to bypass type checking for now
      };

      const result = await dispatch(createStore(storeData as any));
      
      // if successful
      if (createStore.fulfilled.match(result)) {
        setIsSuccess(true);
        clearDraft();
        console.log('Store created successfully');
      } else if (createStore.rejected.match(result)) {
        setSubmitError(result.error.message || 'Failed to create store. Please try again.');
      }
    } catch (error) {
      console.error('Store creation error:', error);
      setSubmitError('An unexpected error occurred. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  
  return (
    <div className="relative flex flex-col justify-evenly w-full h-full lg:max-w-[50vh] mx-auto p-[1.2vh] bg-white">
      <div className="relative flex items-center justify-center w-full text-cenrte text-[4vh] font-[500] h-[15%]">
        <img 
          src="https://storage.googleapis.com/the-mall-uploads-giza/stores/68726dde5987f5810dee5a8a/images/mall%20image.webp" 
          alt="Mall theme image" 
          className="absolute inset-0 w-full h-full object-cover rounded-[.55vh]" 
        />
        {/* Only show this if next clicked is true */}
        <p className="font-[Lato] text-white text-[4vh] z-1 text-shadow-2xs font-[500] opacity-85">Create Your Store</p>
      </div>
      <AnimatePresence custom={direction} mode="wait">
        <motion.div
          key={step}
          custom={direction}
          variants={{
            enter: (dir: number) => ({ x: dir > 0 ? '100%' : '-100%', opacity: 0 }),
            center: { x: 0, opacity: 1 },
            exit: (dir: number) => ({ x: dir > 0 ? '-100%' : '100%', opacity: 0 }),
          }}
          initial="enter"
          animate="center"
          exit="exit"
          transition={{ duration: 0.3 }}
          className="w-full h-[70%] z-10 "
        >
          <StepComponent />
        </motion.div>
      </AnimatePresence>

      <div className="flex flex-row justify-between items-center h-[7%] z-10">
        <button
            type="button"
            onClick={step === 0 ? () => navigate(-1) : prevStep}
            className="px-[1.2vh] py-[.3vh] text-[2vh] text-black border rounded-[.45vh] flex items-center gap-1"
            >
            {step === 0 ? "Close" : "Back"}
        </button>
        {step === steps.length - 1 ? (
            <button
                type="button"
                onClick={handleSubmit} 
                className="px-[1.2vh] py-[.3vh] text-[2vh] text-white bg-black rounded-[.45vh] hover:scale-105 hover:opacity-80 disabled:bg-gray-500"
            >
                {isLoading ? (
                  <TbLoader3 className="w-6 h-6 animate-spin mx-auto" />
                ) : (
                  "Submit"
                )}
            </button>
              ) : (
            <button
                onClick={handleNextStep}
                disabled={step === steps.length - 1}
                className="px-[1.2vh] py-[.3vh] text-[2vh] text-white bg-black rounded-[.45vh] hover:scale-105 hover:opacity-80 disabled:bg-gray-500"
            >
                Next
            </button>
        )}
      </div>

      {/* Error display */}
      {(submitError || storeError) && (
        <div className="text-center text-red-500 text-[1.8vh] mt-2 px-4">
          {submitError || storeError}
        </div>
      )}

      {/* Success case */}
      <AnimatePresence>
          {isSuccess && <StoreSuccessOverlay onClose={() => setIsSuccess(false)}/>}
      </AnimatePresence>
      {/* Background Icon */}
      <div className="absolute z-0 top-10 left-[10%] w-[500px] flex flex-col justify-center opacity-10">
        <LiaStoreSolid size={700} className='mr-80'/>
      </div>
    </div>
  );
};
interface CreateStoreFormProps {
    isDemo?: boolean;
}
const CreateStoreForm: React.FC<CreateStoreFormProps> = ({isDemo}) => (
  <FormProvider>
    <CreateStoreFormInner isDemo={isDemo}/>
  </FormProvider>
);

export default CreateStoreForm;
