import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FormProvider, useFormContext } from './context/FormContext';
import StepBasic from './steps/StepBasic';
import StepTrade from './steps/StepTrade';
import StepBusinessHours from './steps/StepBusinessHours';
import StepLocation from './steps/StepLocation';
import StepAbout from './steps/StepAbout';
import { LiaStoreSolid } from 'react-icons/lia';
import StoreSuccessOverlay from '../StoreSuccessOverlay';
import { createStore } from '../../../../features/stores/storeSlice';
import { useAppDispatch, useAppSelector } from '../../../../app/hooks';
import StepSocials from './steps/StepSocials';
import StepDelivers from './steps/StepDelivers';
import { TbLoader3 } from 'react-icons/tb';
import { useNavigate } from 'react-router-dom';
import { IoClose, IoAlertCircle } from 'react-icons/io5';
import { FaCheck } from 'react-icons/fa';

const steps = [StepBasic, StepTrade, StepBusinessHours, StepLocation, StepDelivers, StepAbout, StepSocials];

const stepTitles = [
  'Basic Details',
  'What You Sell',
  'Operating Hours',
  'Location',
  'Delivery',
  'About',
  'Socials'
];

interface CreateStoreFormInnerProps {
    isDemo?: boolean;
}

const CreateStoreFormInner: React.FC<CreateStoreFormInnerProps> = ({ isDemo = false, }) => {
   const dispatch = useAppDispatch();
   const navigate = useNavigate();
   const { step, direction, nextStep, prevStep, validateCurrentStep, form, setNextClicked, clearDraft, resetForm } = useFormContext();
   const [isSuccess, setIsSuccess] = useState(false);
   const [submitError, setSubmitError] = useState<string | null>(null);
   const [ isSubmitting, setIsSubmitting ] = useState(false);
   const isLoading = useAppSelector((state) => state.stores.isLoading || state.layout.isLoading);
   const storeError = useAppSelector((state) => state.stores.error);
   const user = useAppSelector((state) => state.user.user);
   
  const StepComponent = steps[step];

  // Track which steps have been completed (have valid data)
  const [completedSteps, setCompletedSteps] = useState<Set<number>>(new Set());

  const handleNextStep = () => {
    setNextClicked(true);
    setSubmitError(null);
    
    // Validate current step
    const isValid = validateCurrentStep();
    
    if (isValid) {
      // Mark current step as completed
      setCompletedSteps(prev => new Set(prev).add(step));
      nextStep();
    }
  };

  const handlePrevStep = () => {
    setSubmitError(null);
    prevStep();
  };

  const handleClose = () => {
    if (window.confirm('Are you sure you want to close? Your progress will be saved as a draft.')) {
      navigate(-1);
    }
  };

  const handleReset = () => {
    if (window.confirm('Are you sure you want to start over? This will clear all your progress.')) {
      resetForm();
      setCompletedSteps(new Set());
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);
    setIsSubmitting(true);
    
    try {
      // Validate all required fields before submission
      if (!form.name.trim()) {
        setSubmitError('Store name is required');
        setNextClicked(true);
        return;
      }
      
      if (!form.contact.phone || !/^[0-9]{10}$/.test(form.contact.phone)) {
        setSubmitError('Valid phone number is required (10 digits)');
        return;
      }
      
      if (!form.contact.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.contact.email)) {
        setSubmitError('Valid email address is required');
        return;
      }
      
      if (!form.departments.length) {
        setSubmitError('Please select a department');
        return;
      }
      
      if (!form.location.address) {
        setSubmitError('Store location is required');
        return;
      }

      if (!user?._id) {
        setSubmitError('User authentication required. Please log in and try again.');
        return;
      }

      const storeData = {
        ...form,
        isDemo,
        slug: '', // Will be generated by backend
        description: form.about || '',
        thumbnails: {
          storeCard: form.thumbnail || '',
          profily: form.thumbnail || ''
        },
        website: {
          source: 'internal',
        },
        categories: {
          products: [],
          services: [],
          rentals: [],
          donations: []
        },
        isVerified: false,
        likes: {
          count: 0,
          users: []
        },
        visits: 0,
        location: {
          type: 'Point',
          coordinates: [form.location.coordinates[0], form.location.coordinates[1]], // [lng, lat]
          nickname: form.location.nickname,
          address: form.location.address
        },
        socials: form.socials?.map(social => ({
          platform: social.platform as "facebook" | "twitter" | "instagram" | "linkedin" | "pinterest" | "youtube" | "whatsapp" | "phone",
          url: social.url
        })) || [],
        operationTimes: form.operationTimes as any // Cast to bypass type checking for now
      };

      const result = await dispatch(createStore(storeData as any));
      
      // if successful
      if (createStore.fulfilled.match(result)) {
        setIsSuccess(true);
        clearDraft();
        console.log('Store created successfully');
      } else if (createStore.rejected.match(result)) {
        setSubmitError(result.error.message || 'Failed to create store. Please try again.');
      }
    } catch (error) {
      console.error('Store creation error:', error);
      setSubmitError('An unexpected error occurred. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Step Progress Indicator Component
  const StepProgress = () => (
    <div className="w-full mb-4">
      <div className="flex items-center justify-between relative">
        {/* Progress Line Background */}
        <div className="absolute left-0 top-1/2 transform -translate-y-1/2 w-full h-[.4vh] bg-gray-200 rounded"></div>
        {/* Progress Line Fill */}
        <div 
          className="absolute left-0 top-1/2 transform -translate-y-1/2 h-[.4vh] bg-indigo-600 rounded transition-all duration-300"
          style={{ width: `${(step / (steps.length - 1)) * 100}%` }}
        ></div>
        
        {/* Step Circles */}
        {steps.map((_, index) => {
          const isCompleted = completedSteps.has(index) || index < step;
          const isCurrent = index === step;
          
          return (
            <div key={index} className="relative z-10 flex flex-col items-center">
              <button
                type="button"
                onClick={() => {
                  // Only allow going back to completed steps
                  if (index < step || completedSteps.has(index)) {
                    // Navigate to that step
                    while (step > index) {
                      prevStep();
                    }
                  }
                }}
                disabled={index > step && !completedSteps.has(index)}
                className={`w-[3vh] h-[3vh] rounded-full flex items-center justify-center text-[1.8vh] font-medium transition-all duration-200 
                  ${isCompleted 
                    ? 'bg-indigo-600 text-white hover:bg-indigo-700' 
                    : isCurrent 
                      ? 'bg-indigo-600 text-white ring-4 ring-indigo-200' 
                      : 'bg-gray-200 text-gray-500 hover:bg-gray-300'}
                  ${index > step && !completedSteps.has(index) ? 'cursor-not-allowed' : 'cursor-pointer'}`}
              >
                {isCompleted ? <FaCheck size={12} /> : index + 1}
              </button>
              <span className={`text-[1.4vh] mt-1 hidden sm:block ${isCurrent ? 'text-indigo-600 font-medium' : 'text-gray-500'}`}>
                {stepTitles[index].split(' ')[0]}
              </span>
            </div>
          );
        })}
      </div>
    </div>
  );
  
  return (
    <div className="relative flex flex-col w-full h-full lg:max-w-[55vh] mx-auto p-4 bg-white shadow-xl rounded-2xl border border-gray-100">
      {/* Header Section */}
      <div className="relative flex items-center justify-center w-full text-center h-16 mb-2">
        <img 
          src="https://storage.googleapis.com/the-mall-uploads-giza/stores/68726dde5987f5810dee5a8a/images/mall%20image.webp" 
          alt="Mall theme image" 
          className="absolute inset-0 w-full h-full object-cover rounded-xl" 
        />
        <div className="absolute inset-0 bg-gradient-to-r from-indigo-900/70 to-purple-900/70 rounded-xl"></div>
        <p className="font-[Lato] text-white text-[3.5vh] z-10 font-semibold drop-shadow-lg">Create Your Store</p>
      </div>
      
      {/* Step Progress Indicator */}
      <StepProgress />
      
      {/* Current Step Title */}
      <div className="text-center mb-[1.2vh]">
        <h2 className="text-lg font-semibold text-gray-800">{stepTitles[step]}</h2>
        <p className="text-xs text-gray-500">Step {step + 1} of {steps.length}</p>
      </div>

      <AnimatePresence custom={direction} mode="wait">
        <motion.div
          key={step}
          custom={direction}
          variants={{
            enter: (dir: number) => ({ x: dir > 0 ? '100%' : '-100%', opacity: 0 }),
            center: { x: 0, opacity: 1 },
            exit: (dir: number) => ({ x: dir > 0 ? '-100%' : '100%', opacity: 0 }),
          }}
          initial="enter"
          animate="center"
          exit="exit"
          transition={{ duration: 0.3 }}
          className="flex-1 overflow-y-auto min-h-0"
        >
          <StepComponent />
        </motion.div>
      </AnimatePresence>
      
      {/* Error display */}
      {(submitError || storeError) && (
        <motion.div 
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex items-center gap-2 text-red-600 text-[1.8vh] bg-red-50 p-3 rounded-lg border border-red-200 mb-3"
        >
          <IoAlertCircle size={18} className="flex-shrink-0" />
          <span>{submitError || storeError}</span>
        </motion.div>
      )}

      <div className="flex flex-row justify-between items-center pt-3 border-t border-gray-100 mt-auto">
        <button
            type="button"
            onClick={step === 0 ? handleClose : handlePrevStep}
            className="px-[1.6vh] py-[1vh] text-[1.8vh] font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors flex items-center gap-2"
        >
            {step === 0 ? (
              <>
                <IoClose size={18} />
                Close
              </>
            ) : (
              'Back'
            )}
        </button>
        
        {/* Step indicator dots for mobile */}
        <div className="flex sm:hidden gap-1">
          {steps.map((_, index) => (
            <div 
              key={index} 
              className={`w-[.8vh] h-[.8vh] rounded-full transition-colors ${index === step ? 'bg-indigo-600' : index < step ? 'bg-indigo-300' : 'bg-gray-300'}`}
            />
          ))}
        </div>
        
        {step === steps.length - 1 ? (
            <button
                type="button"
                onClick={handleSubmit} 
                className="px-[2.2vh] py-[1vh] text-[1.8vh] font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 transition-all hover:scale-105 disabled:bg-gray-400 disabled:hover:scale-100 flex items-center gap-2 shadow-md"
                disabled={isLoading || isSubmitting}
            >
                {isLoading || isSubmitting ? (
                  <>
                    <TbLoader3 className="w-4 h-4 animate-spin" />
                    Creating...
                  </>
                ) : (
                  <>
                    <FaCheck size={14} />
                    Create Store
                  </>
                )}
            </button>
              ) : (
            <button
                onClick={handleNextStep}
                disabled={step === steps.length - 1}
                className="px-[2.2vh] py-[1vh] text-[1.8vh] font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 transition-all hover:scale-105 disabled:bg-gray-400 disabled:hover:scale-100 flex items-center gap-2 shadow-md"
            >
                Next
            </button>
        )}
      </div>

      

      {/* Success case */}
      <AnimatePresence>
          {isSuccess && <StoreSuccessOverlay onClose={() => setIsSuccess(false)}/>}
      </AnimatePresence>
      {/* Background Icon */}
      <div className="absolute z-0 top-20 left-4 w-48 flex flex-col justify-center opacity-5 pointer-events-none">
        <LiaStoreSolid size={200} className='text-indigo-900'/>
      </div>
    </div>
  );
};

interface CreateStoreFormProps {
    isDemo?: boolean;
}

const CreateStoreForm: React.FC<CreateStoreFormProps> = ({isDemo}) => (
  <FormProvider>
    <CreateStoreFormInner isDemo={isDemo}/>
  </FormProvider>
);

export default CreateStoreForm;
